<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:08:16.
 */
class gerador_datatemplateModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var gerador_datatemplateModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new gerador_datatemplateModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers gerador_datatemplateModel::getTemplate
     * @todo   Implement testGetTemplate().
     */
    public function testGetTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
