<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:08:08.
 */
class gerador_widgetModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var gerador_widgetModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new gerador_widgetModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers gerador_widgetModel::getWidgetsByPlugin
     * @todo   Implement testGetWidgetsByPlugin().
     */
    public function testGetWidgetsByPlugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gerador_widgetModel::gerar
     * @todo   Implement testGerar().
     */
    public function testGerar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
